TARGET = proj7
LIBS = -lm #Math Library, just a placeholder
HEADERS = Node.h DataType.h ArrayQueue.h NodeQueue.h 
OBJECTS = proj7.o Node.o DataType.o ArrayQueue.o NodeQueue.o
CXX = g++
CXX_FLAGS = -Wall -std=c++11 #C++11 just for reference, not necessary

.PHONY: default all clean

default: $(TARGET)
all: default

%.o: %.cpp $(HEADERS)
	$(CXX) $(CXX_FLAGS) -c $< -o $@

$(TARGET): $(OBJECTS)
	$(CXX) $(CXX_FLAGS) $(OBJECTS) $(LIBS) -o $@

clean:
	-rm -f *.o
	-rm -f $(TARGET)